services:
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    hostname: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    restart: always
    environment:
      - BROKER_CREDENTIALS=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
    depends_on:
      - rabbitmq
      - redis
    deploy:
      replicas: 5

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${BROKER_URL}
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH}
    depends_on:
      - rabbitmq
      - redis
    command: >
      celery flower
      --broker=${BROKER_URL}
      --broker_api=http://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:15672/api/

volumes:
  rabbitmq_data:
  rabbitmq_logs:
